# Generated by Django 5.2.4 on 2025-08-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_orden_itemorden"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallecompra",
            name="imagen_producto",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
